# Single Source Shortest Paths (Dijkstra's algorithm)

## Weighted Matrix

In [ ]:
def dijkstra(WMat,s):
    (rows,cols,x) = WMat.shape
    infinity = np.max(WMat)*rows+1
    (visited,distance) = ({},{})
    for v in range(rows):
        (visited[v],distance[v]) = (False,infinity)

    distance[s] = 0

    for u in range(rows):
        nextd = min([distance[v] for v in range(rows)
                        if not visited[v]])
        nextvlist = [v for v in range(rows)
                        if (not visited[v]) and
                            distance[v] == nextd]
        if nextvlist == []:
            break
        nextv = min(nextvlist)

        visited[nextv] = True
        for v in range(cols):
            if WMat[nextv,v,0] == 1 and (not visited[v]):
                distance[v] = min(distance[v],distance[nextv] + WMat[nextv,v,1])
    return(distance)

In [ ]:
import numpy as np
size = int(input())
edges = eval(input())
W = np.zeros(shape=(size,size,2))
for (i,j,w) in edges:
    W[i,j,0] = 1
    W[i,j,1] = w
dijkstra(W,0)

7
[(0,1,10),(0,2,50),(0,3,300),(5,6,45),(2,1,30),(6,4,37),(1,6,65),(2,5,76),(1,3,40),(3,4,60),(2,4,20)]


{0: 0, 1: 10.0, 2: 50.0, 3: 50.0, 4: 70.0, 5: 126.0, 6: 75.0}

## Weighted List

In [ ]:
def dijkstralist(WList,s):
    infinity = 1 + len(WList.keys())*max([d for u in WList.keys()
                           for (v,d) in WList[u]])
    (visited,distance) = ({},{})
    for v in WList.keys():
        (visited[v],distance[v]) = (False,infinity)

    distance[s] = 0

    for u in WList.keys():
        nextd = min([distance[v] for v in WList.keys() #calculates the minimum distance from the source to any unvisited vertex.
                        if not visited[v]])
        nextvlist = [v for v in WList.keys() #is a list of vertices with the distance equal to nextd and that have not been visited yet.
                        if (not visited[v]) and
                            distance[v] == nextd]
        if nextvlist == []:
            break
        nextv = min(nextvlist)
        visited[nextv] = True
        for (v,d) in WList[nextv]: #nextv: [(v1,d1), (v2,d2), (v3,d3)...]
            if not visited[v]:
                distance[v] = min(distance[v],distance[nextv]+d)
    return(distance)

In [ ]:
min(float('inf'),float('inf'))

inf

In [ ]:
size = int(input())
edges = eval(input())
WL = {}
for i in range(size):
    WL[i] = []
for ed in edges:
    WL[ed[0]].append((ed[1],ed[2]))
    WL[ed[1]].append((ed[0],ed[2]))
WL

7
[(0,1,10),(0,2,50),(0,3,300),(5,6,45),(2,1,30),(6,4,37),(1,6,65),(2,5,76),(1,3,40),(3,4,60),(2,4,20)]


{0: [(1, 10), (2, 50), (3, 300)],
 1: [(0, 10), (2, 30), (6, 65), (3, 40)],
 2: [(0, 50), (1, 30), (5, 76), (4, 20)],
 3: [(0, 300), (1, 40), (4, 60)],
 4: [(6, 37), (3, 60), (2, 20)],
 5: [(6, 45), (2, 76)],
 6: [(5, 45), (4, 37), (1, 65)]}

In [ ]:
dijkstralist(WL,0)

0
[0]
0
10
[1]
1
40
[2]
2
50
[3]
3
60
[4]
4
75
[6]
6
116
[5]
5


{0: 0, 1: 10, 2: 40, 3: 50, 4: 60, 5: 116, 6: 75}

## Single Source Shortest Paths with Negative Weights (Bellman-Ford Algorithm)

## Weighted Matrix

In [ ]:
def bellmanford(WMat,s):
    (rows,cols,x) = WMat.shape
    infinity = np.max(WMat)*rows+1
    distance = {}
    for v in range(rows):
        distance[v] = infinity

    distance[s] = 0

    for i in range(rows):
        for u in range(rows):
            for v in range(cols):
                if WMat[u,v,0] == 1:
                    distance[v] = min(distance[v], distance[u]
                                                   + WMat[u,v,1])
    return(distance)

In [ ]:
import numpy as np
size = int(input())
edges = eval(input())
W = np.zeros(shape=(size,size,2))
for (i,j,w) in edges:
    W[i,j,0] = 1
    W[i,j,1] = w
bellmanford(W,0)

7
[(0,1,10),(0,2,50),(0,3,300),(5,6,45),(2,1,30),(6,4,37),(1,6,65),(2,5,76),(1,3,40),(3,4,60),(2,4,20)]


{0: 0, 1: 10.0, 2: 50.0, 3: 50.0, 4: 70.0, 5: 126.0, 6: 75.0}

## Weighted Adjacency List

In [ ]:
def bellmanfordlist(WList,s):
    infinity = 10^90
    distance = {}
    for v in WList.keys():
        distance[v] = infinity

    distance[s] = 0

    for i in WList.keys():
        for u in WList.keys():
            for (v,d) in WList[u]:
                distance[v] = min(distance[v], distance[u] + d)
    return(distance)

In [ ]:
size = int(input())
edges = eval(input())
WL = {}
for i in range(size):
    WL[i] = []
for ed in edges:
    WL[ed[0]].append((ed[1],ed[2]))
    WL[ed[1]].append((ed[0],ed[2]))


7
[(0,1,10),(0,2,50),(0,3,300),(5,6,45),(2,1,30),(6,4,37),(1,6,65),(2,5,76),(1,3,40),(3,4,60),(2,4,20)]


In [ ]:
bellmanfordlist(WL,0)

{0: 0, 1: 10, 2: 40, 3: 50, 4: 60, 5: 80, 6: 75}

# All Pairs Shortest Paths (Floyd-Warshall Algorithm)_O(n^3)

### Adjacency matrix

In [ ]:
def floydwarshall(WMat):
    (rows,cols,x) = WMat.shape
    infinity = np.max(WMat)*rows*rows+1

    SP = np.zeros(shape=(rows,cols,cols+1))
    for i in range(rows):
        for j in range(cols):
            SP[i,j,0] = infinity

    for i in range(rows):
        for j in range(cols):
            if WMat[i,j,0] == 1:
                SP[i,j,0] = WMat[i,j,1]

    for k in range(1,cols+1):
        for i in range(rows):
            for j in range(cols):
                SP[i,j,k] = min(SP[i,j,k-1],
                                SP[i,k-1,k-1]+SP[k-1,j,k-1])
    return(SP[:,:,cols])


In [ ]:
import numpy as np
size = int(input())
edges = eval(input())
W = np.zeros(shape=(size,size,2))
for (i,j,w) in edges:
    W[i,j,0] = 1
    W[i,j,1] = w
floydwarshall(W)

7
[(0,1,10),(0,2,50),(0,3,300),(5,6,45),(2,1,30),(6,4,37),(1,6,65),(2,5,76),(1,3,40),(3,4,60),(2,4,20)]


array([[1.4701e+04, 1.0000e+01, 5.0000e+01, 5.0000e+01, 7.0000e+01,
        1.2600e+02, 7.5000e+01],
       [1.4701e+04, 1.4701e+04, 1.4701e+04, 4.0000e+01, 1.0000e+02,
        1.4701e+04, 6.5000e+01],
       [1.4701e+04, 3.0000e+01, 1.4701e+04, 7.0000e+01, 2.0000e+01,
        7.6000e+01, 9.5000e+01],
       [1.4701e+04, 1.4701e+04, 1.4701e+04, 1.4701e+04, 6.0000e+01,
        1.4701e+04, 1.4701e+04],
       [1.4701e+04, 1.4701e+04, 1.4701e+04, 1.4701e+04, 1.4701e+04,
        1.4701e+04, 1.4701e+04],
       [1.4701e+04, 1.4701e+04, 1.4701e+04, 1.4701e+04, 8.2000e+01,
        1.4701e+04, 4.5000e+01],
       [1.4701e+04, 1.4701e+04, 1.4701e+04, 1.4701e+04, 3.7000e+01,
        1.4701e+04, 1.4701e+04]])

### Adjacency List

In [ ]:
def floydwarshall(WMat):
    (rows,cols,x) = WMat.shape
    infinity = np.max(WMat)*rows*rows+1

    SP = np.zeros(shape=(rows,cols,cols+1))
    for i in range(rows):
        for j in range(cols):
            SP[i,j,0] = infinity

    for i in range(rows):
        for j in range(cols):
            if WMat[i,j,0] == 1:
                SP[i,j,0] = WMat[i,j,1]

    for k in range(1,cols+1):
        for i in range(rows):
            for j in range(cols):
                SP[i,j,k] = min(SP[i,j,k-1],
                                SP[i,k-1,k-1]+SP[k-1,j,k-1])
    return(SP[:,:,cols])

In [ ]:
size = int(input())
edges = eval(input())
WL = {}
for i in range(size):
    WL[i] = []
for ed in edges:
    WL[ed[0]].append((ed[1],ed[2]))
    WL[ed[1]].append((ed[0],ed[2]))

7
[(0,1,10),(0,2,50),(0,3,300),(5,6,45),(2,1,30),(6,4,37),(1,6,65),(2,5,76),(1,3,40),(3,4,60),(2,4,20)]


In [ ]:
WL

{0: [(1, 10), (2, 50), (3, 300)],
 1: [(0, 10), (2, 30), (6, 65), (3, 40)],
 2: [(0, 50), (1, 30), (5, 76), (4, 20)],
 3: [(0, 300), (1, 40), (4, 60)],
 4: [(6, 37), (3, 60), (2, 20)],
 5: [(6, 45), (2, 76)],
 6: [(5, 45), (4, 37), (1, 65)]}

In [ ]:
floydwarshall(WL)

ValueError: ignored

In [ ]:
import numpy as np

def create_adjacency_matrix(adjacency_list):
    num_vertices = len(adjacency_list)
    adjacency_matrix = np.zeros((num_vertices, num_vertices))

    for vertex, neighbors in adjacency_list.items():
        for neighbor, weight in neighbors:
            adjacency_matrix[vertex][neighbor] = int(weight)

    return adjacency_matrix


# Example weighted adjacency list
adjacency_list = {
    0: [(1, 10), (2, 50), (3, 300)],
    1: [(0, 10), (2, 30), (6, 65), (3, 40)],
    2: [(0, 50), (1, 30), (5, 76), (4, 20)],
    3: [(0, 300), (1, 40), (4, 60)],
    4: [(6, 37), (3, 60), (2, 20)],
    5: [(6, 45), (2, 76)],
    6: [(5, 45), (4, 37), (1, 65)]
}

adjacency_matrix = create_adjacency_matrix(adjacency_list)

# Print the adjacency matrix
print(adjacency_matrix)


[[  0.  10.  50. 300.   0.   0.   0.]
 [ 10.   0.  30.  40.   0.   0.  65.]
 [ 50.  30.   0.   0.  20.  76.   0.]
 [300.  40.   0.   0.  60.   0.   0.]
 [  0.   0.  20.  60.   0.   0.  37.]
 [  0.   0.  76.   0.   0.   0.  45.]
 [  0.  65.   0.   0.  37.  45.   0.]]


In [ ]:
dijkstra([[ (0, 0),  (1, 10),  (1, 50),  (1, 300),  (0, 0),  (0, 0),  (0, 0)],
 [ (1, 10),  (0, 0),  (1, 30),  (1, 40),  (0, 0),  (0, 0),  (1, 65)],
 [ (1, 50),  (1, 30),  (0, 0),  (0, 0),  (1, 20),  (1, 76),  (0, 0)],
 [ (1, 300),  (1, 40),  (0, 0),  (0, 0),  (1, 60),  (0, 0),  (0, 0)],
 [ (0, 0),  (0, 0),  (1, 20),  (1, 60),  (0, 0),  (0, 0),  (1, 37)],
 [ (0, 0),  (0, 0),  (1, 76),  (0, 0),  (0, 0),  (0, 0),  (1, 45)],
 [ (0, 0),  (1, 65),  (0, 0),  (0, 0),  (1, 37),  (1, 45),  (0, 0)]],3)

TypeError: ignored

# Minimum Cost Spanning Trees Kruskal's Algorithm

In [ ]:
def kruskal(WList):
    (edges,component,TE) = ([],{},[])
    for u in WList.keys():
        # Weight as first component to sort easily
        edges.extend([(d,u,v) for (v,d) in WList[u]])
        component[u] = u
    edges.sort()

    for (d,u,v) in edges:
        if component[u] != component[v]:
            TE.append((u,v))
            c = component[u]
            for w in WList.keys():
                if component[w] == c:
                    component[w] = component[v]
    return(TE)



In [ ]:
size = int(input())
edges = eval(input())
WL = {}
for i in range(size):
    WL[i] = []
for ed in edges:
    WL[ed[0]].append((ed[1],ed[2]))
    WL[ed[1]].append((ed[0],ed[2]))
print(WL)
print(kruskal(WL))

7
[(0,1,10),(0,2,50),(0,3,300),(5,6,45),(2,1,30),(6,4,37),(1,6,65),(2,5,76),(1,3,40),(3,4,60),(2,4,20)]
{0: [(1, 10), (2, 50), (3, 300)], 1: [(0, 10), (2, 30), (6, 65), (3, 40)], 2: [(0, 50), (1, 30), (5, 76), (4, 20)], 3: [(0, 300), (1, 40), (4, 60)], 4: [(6, 37), (3, 60), (2, 20)], 5: [(6, 45), (2, 76)], 6: [(5, 45), (4, 37), (1, 65)]}
[(0, 1), (2, 4), (1, 2), (4, 6), (1, 3), (5, 6)]


In [ ]:
size = int(input())
edges = eval(input())
WL = {}
for i in range(size):
    WL[i] = []
for ed in edges:
    WL[ed[0]].append((ed[1],ed[2]))


4
[(0,1,10),(0,2,-5),(0,3,2),(3,2,-5),(2,1,-20),(1,3,10)]


In [ ]:
WL

{0: [(1, 10), (2, -5), (3, 2)], 1: [(3, 10)], 2: [(1, -20)], 3: [(2, -5)]}

In [ ]:
def IsNegativeWeightCyclePresent(WList):
  for s in WList.keys():
      infinity = float('inf')
      (distance,testd) = ({},{})
      for v in WList.keys():
          distance[v] = infinity
          testd[v] = infinity

      distance[s] = 0
      testd[s]=0

      for i in WList.keys():
          for u in WList.keys():
              for (v,d) in WList[u]:
                  distance[v] = min(distance[v], distance[u] + d)

      for i in range(len(WList.keys())+1):
          for u in WList.keys():
              for (v,d) in WList[u]:
                  testd[v] = min(testd[v], testd[u] + d)
      return(distance!=testd)

In [ ]:
size = int(input())
edges = eval(input())
WL = {}
for i in range(size):
    WL[i] = []
for ed in edges:
    WL[ed[0]].append((ed[1],ed[2]))
WL

4
[(0,1,-10),(1,2,-20),(2,3,-20)]


{0: [(1, -10)], 1: [(2, -20)], 2: [(3, -20)], 3: []}

In [ ]:
IsNegativeWeightCyclePresent(WL)

False

In [ ]:
bellmanfordlist(WL,2) == bellmanfordlist(WL,3)

False

In [ ]:
import heapq

def mergeKLists(lists):
    merged = []
    heap = []

    # Initialize the heap with the first element from each list
    for i, lst in enumerate(lists): #enumerate(lists) gives (position, position of each list)
        if lst: #if lst is not empty:
            heapq.heappush(heap, (lst[0], i, 0))  '''push the tuple (value of the first element of the list, list_index, element_index)
            into the heap'''

    while heap: #while heap is not empty
        value, list_index, element_index = heapq.heappop(heap)
        merged.append(value)

        # Move to the next element in the list
        if element_index + 1 < len(lists[list_index]):
            next_element = lists[list_index][element_index + 1]
            heapq.heappush(heap, (next_element, list_index, element_index + 1))

    return merged


k = int(input())
LL=[]
for i in range(k):
    subL = [int(item) for item in input().split(" ")]
    LL.append(subL)
print(*mergeKLists(LL))

In [ ]:
heap = []
merged = []
# Initialize the heap with the first element from each list
for i, lst in enumerate([[4, 5], [8, 26, 69]]): #enumerate(lists) gives (position, position of each list)
    if lst: #if lst is not empty:
        heapq.heappush(heap, (lst[0], i, 0))
print('heap =',heap)
iter =0
while heap: #while heap is not empty
        iter+=1
        value, list_index, element_index = heapq.heappop(heap)
        print('(value, list_index, element_index) at iter =',iter,':',value, list_index, element_index)
        merged.append(value)
        print('merged at iter', iter,':',merged)
        if element_index + 1 < len([[4, 5], [8, 26, 69]][list_index]): #check if there is a next element in the same list from which we popped
            next_element = [[4, 5], [8, 26, 69]][list_index][element_index + 1]
            heapq.heappush(heap, (next_element, list_index, element_index + 1))
        print('heap at iter', iter, ':', heap)
print('merged =',merged)

heap = [(4, 0, 0), (8, 1, 0)]
(value, list_index, element_index) at iter = 1 : 4 0 0
merged at iter 1 : [4]
heap at iter 1 : [(5, 0, 1), (8, 1, 0)]
(value, list_index, element_index) at iter = 2 : 5 0 1
merged at iter 2 : [4, 5]
heap at iter 2 : [(8, 1, 0)]
(value, list_index, element_index) at iter = 3 : 8 1 0
merged at iter 3 : [4, 5, 8]
heap at iter 3 : [(26, 1, 1)]
(value, list_index, element_index) at iter = 4 : 26 1 1
merged at iter 4 : [4, 5, 8, 26]
heap at iter 4 : [(69, 1, 2)]
(value, list_index, element_index) at iter = 5 : 69 1 2
merged at iter 5 : [4, 5, 8, 26, 69]
heap at iter 5 : []
merged = [4, 5, 8, 26, 69]


In [ ]:
LL=[[4, 5], [8, 26, 69]]
for i,lst in enumerate(LL):
  print(i)
  print(lst)


0
[4, 5]
1
[8, 26, 69]


enumerate

In [ ]:
heap, merged

([], [4, 8])

In [ ]:
import heapq
heap = []
heapq.heappush(heap,2)
heapq.heappush(heap,5)
heapq.heappush(heap,9)
heapq.heappush(heap,0)
heapq.heappop(heap)

0

In [ ]:
heap

[2, 5, 9]