Longest Common Subsequnce

In [ ]:
def lcs(u,v):
  import numpy as np
  (m,n) = (len(u),len(v))
  lcs = np.zeros((m+1,n+1)) #(m+1,n+1) for base case
  for i in range(m-1,-1,-1):
    for j in range(n-1,-1,-1):
      if u[i]==v[j]:
        lcs[i,j] = 1+lcs[i+1,j+1]
      else:
        lcs[i,j] = max(lcs[i,j+1],lcs[i+1,j])
  return(lcs[0,0],lcs)

In [ ]:
lcs('secrety','secretary')

(7.0,
 array([[7., 6., 5., 4., 3., 2., 2., 2., 1., 0.],
        [6., 6., 5., 4., 3., 2., 2., 2., 1., 0.],
        [5., 5., 5., 4., 3., 2., 2., 2., 1., 0.],
        [4., 4., 4., 4., 3., 2., 2., 2., 1., 0.],
        [3., 3., 3., 3., 3., 2., 1., 1., 1., 0.],
        [2., 2., 2., 2., 2., 2., 1., 1., 1., 0.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]))

Longest Common Word

In [ ]:
def lcw(u,v):
  import numpy as np
  (m,n)=(len(u),len(v))
  lcw = np.zeros((m+1,n+1))
  maxlcw = 0
  for i in range(m-1,-1,-1):
    for j in range(n-1,-1,-1):
      if u[i]==v[j]:
        lcw[i,j]=1+lcw[i+1,j+1]
      else:
        lcw[i,j]=0
      if lcw[i,j]>maxlcw:
        maxlcw = lcw[i,j]
  return(lcw,maxlcw)

In [ ]:
lcw('secret','secretary')

(array([[6., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 5., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 4., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 3., 0., 0., 0., 1., 0., 0.],
        [0., 1., 0., 0., 2., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]),
 6.0)

In [ ]:
lcw('happy','apple')

(array([[0., 0., 0., 0., 0., 0.],
        [3., 0., 0., 0., 0., 0.],
        [0., 2., 1., 0., 0., 0.],
        [0., 1., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]]),
 3.0)

Longest Decreasing Sequence

In [ ]:
user_input = input()
numbers = user_input.split()
numbers = [int(num) for num in numbers]
def lds(seq):
  L = [0]*len(seq)
  L[0]=1
  path_dic = {}
  for i in range(len(seq)):
    path_dic[seq[i]]=[]
  for i in range(len(seq)):
    for j in range(i):
      if L[j]>L[i] and seq[j]>seq[i]:
        L[i]=L[j]
        path_dic[seq[i]].append(seq[j])
    L[i]+=1
    path_dic[seq[i]].append(seq[i])
    #print('L=',L)
  return(path_dic[seq[L.index(max(L))]])
print(lds(numbers))

0 2 7 3 7 3 8 2 1 0
[0, 2, 3, 2, 1, 0]


In [ ]:
lds([7,9,6,10,5])

[7, 6, 5]

In [ ]:
lds([0, 2, 7, 3, 7, 3, 8, 2, 1, 0])

L= [2, 0, 0, 0, 0, 0, 0, 0, 0, 0]
L= [2, 1, 0, 0, 0, 0, 0, 0, 0, 0]
L= [2, 1, 1, 0, 0, 0, 0, 0, 0, 0]
L= [2, 1, 1, 2, 0, 0, 0, 0, 0, 0]
L= [2, 1, 1, 2, 1, 0, 0, 0, 0, 0]
L= [2, 1, 1, 2, 1, 2, 0, 0, 0, 0]
L= [2, 1, 1, 2, 1, 2, 1, 0, 0, 0]
L= [2, 1, 1, 2, 1, 2, 1, 3, 0, 0]
L= [2, 1, 1, 2, 1, 2, 1, 3, 4, 0]
L= [2, 1, 1, 2, 1, 2, 1, 3, 4, 5]


5

In [ ]:
lds([11, 16, 32, 60, 50, 58, 8, 59, 45, 48])

L= [2, 0, 0, 0, 0, 0, 0, 0, 0, 0]
L= [2, 1, 0, 0, 0, 0, 0, 0, 0, 0]
L= [2, 1, 1, 0, 0, 0, 0, 0, 0, 0]
L= [2, 1, 1, 1, 0, 0, 0, 0, 0, 0]
L= [2, 1, 1, 1, 2, 0, 0, 0, 0, 0]
L= [2, 1, 1, 1, 2, 2, 0, 0, 0, 0]
L= [2, 1, 1, 1, 2, 2, 3, 0, 0, 0]
L= [2, 1, 1, 1, 2, 2, 3, 2, 0, 0]
L= [2, 1, 1, 1, 2, 2, 3, 2, 3, 0]
L= [2, 1, 1, 1, 2, 2, 3, 2, 3, 3]


3

In [ ]:
lds([0,2,3,4,1])

L= [2, 0, 0, 0, 0]
L= [2, 1, 0, 0, 0]
L= [2, 1, 1, 0, 0]
L= [2, 1, 1, 1, 0]
L= [2, 1, 1, 1, 2]


2

In [ ]:
M = eval(input())
(x1, y1) = eval(input())
(x2, y2) = eval(input())

def MaxCoinPath(M, x1, y1, x2, y2):
    if x1 >= len(M) or y1 >= len(M[0]) or x2 >= len(M) or y2 >= len(M[0]):
        return 0
    if x2 == x1 and y2 == y1:
        return M[x1][y1]
    else:
        return M[x1][y1] + max(
            MaxCoinPath(M, x1 + 1, y1, x2, y2),
            MaxCoinPath(M, x1, y1 + 1, x2, y2)
        )

print(MaxCoinPath(M, x1, y1, x2, y2))


[[2,1,3,2,5],[3,5,2,4,6],[7,6,1,3,2],[2,9,4,7,8],[1,4,5,11,3]]
(0,0)
(4,4)
52


Making a word from a list of its subwords

In [ ]:
def constructWord(w,L):
  #word = []
  count = 0
  if w =='':
    count+=1
  if w in L:
    #word.append([w])
    count+=1
  for i in range(len(L)):
    if L[i] in w:
      return(constructWord(w.replace(L[i],''),L.remove(L[i])))
  return(count)

In [ ]:
constructWord('apple', ['ap', 'pple', 'app', 'apl', 'appl', 'le', 'ple'])

TypeError: ignored

In [ ]:
'pl' in 'apple'

True

In [ ]:
'ale' in 'apple'

False

In [ ]:
constructword('apple',['ale','pp'])

[]

In [ ]:
'apple'.replace('app','')

'le'

In [ ]:
'apple'[:len('ppl')]

'app'

In [ ]:
memo = {}
def constructWord(word, wordList):
    if word == '':
        return [[]]
    if word in memo.keys():
        return memo[word]
    totalwordlist = []
    for subword in wordList:
        if subword == word[:len(subword)]:
            subwordList = constructWord(word[len(subword):], wordList)
            print('swl= ',subwordList)
            totalwordlist.extend([[subword] + lst for lst in subwordList])
            print('twl= ',totalwordlist)
    memo[word] = totalwordlist
    return totalwordlist

In [ ]:
constructWord('apple', ['ap', 'pple', 'app', 'apl', 'appl', 'le', 'ple'])

swl=  [[]]
twl=  [['ple']]
swl=  [['ple']]
twl=  [['ap', 'ple']]
swl=  [[]]
twl=  [['le']]
swl=  [['le']]
twl=  [['ap', 'ple'], ['app', 'le']]
swl=  []
twl=  [['ap', 'ple'], ['app', 'le']]


[['ap', 'ple'], ['app', 'le']]

In [ ]:
print('ap' == 'apple'[:2])
print('apple'[2:])

True
ple


In [ ]:
a = 1
b = [[4,5,6]]
[[a] + lst for lst in b]

[[1, 4, 5, 6]]

In [ ]:
[[1]]+[1,2,3]

[[1], 1, 2, 3]

In [ ]:
import scipy.stats as stats

def standard_normal_cdf(x):
    return stats.norm.cdf(x, loc=0, scale=1)

def standard_gamma_cdf(x):
    return 1- stats.gamma.cdf(515, 250, 0.5)

In [ ]:
1-standard_normal_cdf(0.474)

0.3177499536125785

In [ ]:
import scipy.stats as stats

alpha = 250
beta = 0.5

x = 515  # The value at which you want to calculate the CDF
cdf = 1-stats.gamma.cdf(x, a=alpha, scale=1/beta)

print("CDF:", cdf)


CDF: 0.3118153512145869


In [ ]:
import math

In [ ]:
15/(math.sqrt(10))

4.743416490252569

Grid path

In [8]:
def unique_path():
  import numpy as np
  mat = np.zeros((6,11))
  for i in range (6):
    mat[i][0] = 1
  for j in range (11):
    mat[0][j] = 1
  for i in range(1,6):
    for j in range(1,11):
      mat[i][j]=mat[i-1][j] + mat[i][j-1]
      if i==2 and j==4:
        mat[i][j]=0
      if i==4 and j==4:
        mat[i][j]=0
  print(mat)

In [9]:
unique_path()

[[1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00 1.000e+00
  1.000e+00 1.000e+00 1.000e+00 1.000e+00]
 [1.000e+00 2.000e+00 3.000e+00 4.000e+00 5.000e+00 6.000e+00 7.000e+00
  8.000e+00 9.000e+00 1.000e+01 1.100e+01]
 [1.000e+00 3.000e+00 6.000e+00 1.000e+01 0.000e+00 6.000e+00 1.300e+01
  2.100e+01 3.000e+01 4.000e+01 5.100e+01]
 [1.000e+00 4.000e+00 1.000e+01 2.000e+01 2.000e+01 2.600e+01 3.900e+01
  6.000e+01 9.000e+01 1.300e+02 1.810e+02]
 [1.000e+00 5.000e+00 1.500e+01 3.500e+01 0.000e+00 2.600e+01 6.500e+01
  1.250e+02 2.150e+02 3.450e+02 5.260e+02]
 [1.000e+00 6.000e+00 2.100e+01 5.600e+01 5.600e+01 8.200e+01 1.470e+02
  2.720e+02 4.870e+02 8.320e+02 1.358e+03]]


In [17]:
def LCW(u,v):
  import numpy as np
  (m,n) = (len(u),len(v))
  lcw = np.zeros((m+1,n+1))
  maxlcw = 0
  for i in range (m-1,-1,-1):
    for j in range (n-1,-1,-1):
      if (u[i]==v[j]):
        lcw[i,j] = 1 + lcw[i+1,j+1]
      else:
        lcw[i][j]=0
      if lcw[i][j]>maxlcw:
        maxlcw = lcw[i][j]
  return maxlcw

In [18]:
LCW('secret','bisect')

(6, 6)


3.0